apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: my-app-project
spec:
  selector:
    app: my-app
    version: blue  # Change this to 'green' to switch to the green deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
